### ISSUE TITLE
Is it planned to implement a module autocompletion?

### ISSUE THREAD

**Issue by lem0nify** [nim-lang/nimsuggest#102] opened 2018-12-21 04:32 UTC
Symbols autocompletion works pretty properly in VSCode with its extension (for my super-tiny projects at least) but there is no module autocompletion at all.
Don't you think it would be useful if we could type `import str`, press Ctrl+Space and see all modules which names start with "str": `strutils`, `strformat`, `strscans` etc. ?

**Comment by krux02** [comment] 2018-12-21 08:39
There are many features that would be very neat. I saw in Java IDE automatic imports, so you had basically completion for functions that weren't even imported at all. But for me personally, before features are added stability should be improved. It is just a matter of priorities.

**Comment by ghost** [comment] 2020-06-23 21:54
This works just fine now, e.g. if you type "import str" in the vscode nim extension you automatically get autocompletion.

**Comment by ghost** [comment] 2020-06-23 21:55
Ignore my last comment, it seems like vscode-nim has that feature but it's not from nimsuggest - https://github.com/pragmagic/vscode-nim/blob/master/src/nimImports.ts

**Comment by ghost** [comment] 2020-06-23 21:57
Also this seems to be a duplicate of https://github.com/nim-lang/nimsuggest/issues/47

**Comment by gavr123456789** [comment] 2021-04-11 18:32
Can be closed?   
![image](https://user-images.githubusercontent.com/30507409/114316721-5a7db500-9b0d-11eb-898b-49b3a550340f.png)

**Closed as completed** 2021-04-12 11:19 UTC
